name: "prateekshit-website"

navbar:
  title: "My cats' website"
  left:
    - text: "Home"
      href: index.html
  right: 
    - icon: fa-envelope fa-lg
      href: mailto:<ppandey@upenn.edu>
    - icon: fa-github fa-lg
      href: http://github.com/prateekshitpandey/

output:
  html_document:
    theme: darkly